# Generated by Django 3.2.8 on 2021-11-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0002_listedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedquestion',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dsa.question', unique=True),
        ),
    ]
