# Generated by Django 3.2.8 on 2021-11-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0003_alter_listedquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedquestion',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
