# Generated by Django 3.2.8 on 2021-11-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0004_alter_listedquestion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listedquestion',
            old_name='id',
            new_name='question',
        ),
    ]
