# Generated by Django 3.2.8 on 2021-11-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0005_rename_id_listedquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dsa.question'),
        ),
    ]
