# Generated by Django 3.2.8 on 2021-11-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0006_alter_listedquestion_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='done',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
