# Generated by Django 3.2.8 on 2021-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0009_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
